"""Add customers router and relation

Revision ID: 05502c12b18a
Revises: a495c0383373
Create Date: 2021-12-06 09:14:51.500919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05502c12b18a'
down_revision = 'a495c0383373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('genre', sa.String(length=45), nullable=True),
    sa.Column('document_id', sa.String(length=45), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('costomers')
    op.add_column('addresses', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'customer_id')
    op.create_table('costomers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=45), nullable=True),
    sa.Column('document_id', sa.VARCHAR(length=45), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customers')
    # ### end Alembic commands ###
