"""Relation between customers and users

Revision ID: 475648f57fbf
Revises: eea6b7391910
Create Date: 2021-12-07 18:51:31.663020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475648f57fbf'
down_revision = 'eea6b7391910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
