"""Add orders and relations

Revision ID: 814523bc0fc6
Revises: f5eca38ebe0e
Create Date: 2021-12-08 13:15:28.113912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "814523bc0fc6"
down_revision = "f5eca38ebe0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("total_value", sa.Float(precision=10, asdecimal=2), nullable=True),
        sa.Column("payment_form_id", sa.Integer(), nullable=True),
        sa.Column("total_discount", sa.Float(precision=10, asdecimal=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_statuses")
    op.drop_table("order_products")
    op.drop_table("orders")
    # ### end Alembic commands ###
