"""full version

Revision ID: f8d1cd02f3e9
Revises: bd5ef32ed336
Create Date: 2022-01-10 19:36:24.040370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d1cd02f3e9'
down_revision = 'bd5ef32ed336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
